blank_issues_enabled: false
contact_links:
    - name: 📱 @walletconnect/modal-react-native Issue
      url: https://github.com/WalletConnect/modal-react-native/issues
      about: Please report @walletconnect/modal-react-native issues in it's specific repository.
    - name: 🤔 Questions and Help
      url: https://github.com/orgs/WalletConnect/discussions
      about: Looking for help with your app? Please refer to the Wallet Connect community's support resources.
