name: cli-wallet-android

on:
  push:
    branches: [ feat/E2E-maestro ]
  # pull_request:
  #   branches: [ main ]

jobs:    
  maestro-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wallets/rn_cli_wallet
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle      
      - run: touch .env && echo "ENV_PROJECT_ID=${{ secrets.ENV_PROJECT_ID }}\nENV_RELAY_URL=${{ secrets.ENV_RELAY_URL }}" >> .env      
      - run: npm install -g yarn
      - run: yarn
      - run: yarn android:build
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: wallets/rn_cli_wallet/android/app/build/outputs/apk/release/app-release.apk
