# .github/workflows/android.yaml

name: e2e-dapp-android

on:
  push:
    branches: [ feat/E2E-maestro ]
  # pull_request:
  #   branches: [ main ]

jobs:    
  maestro-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dapps/v2Explorer
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle      
      - run: npm install -g yarn
      - run: yarn
      - run: yarn android:build
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: dapps/v2Explorer/android/app/build/outputs/apk/debug/app-debug.apk
